name: build java_liberica

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - main
    paths:
      - java-liberica/**

permissions:
  actions: read
  packages: write

concurrency:
  group: java-liberica-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  push:
    name: "images:ava_${{ matrix.tag }}_liberica"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 8
          - 11
          - 17
          - 21
          - 22
    steps:
      - name: Git checkout for Github repository workspace
        uses: actions/checkout@v4

      - name: Setup QEMU for multiarch builds
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./java-liberica
          platforms: linux/amd64, linux/arm64
          file: ./java-liberica/${{ matrix.tag }}/Dockerfile
          push: true
          tags: ghcr.io/hidencloud/images:java_${{ matrix.tag }}_liberica
